### ISSUE TITLE
installation questions

### ISSUE THREAD

**Issue by bryandickman** [riscv-software-src/homebrew-riscv#122]
Hi,
I've been struggling for a while to build the riscv-gnu-toolchain on my M1 Mac with apple silicon. Tried cloning the toolchain from the GitHub respository and building following the instructions to configure and make, but I am getting errors in my config.log file suggestion arm64 arch incompatibilities in the build process for gcc and gmp.
So I thought I would try Scott's pre build for OSX using brew
got as far as the make and it has installed the tools.
So I then tried to run the test as suggested 
brew test riscv-tools 
but I get the following error 
==> Testing riscv-software-src/riscv/riscv-tools
==> /usr/local/opt/riscv-gnu-toolchain/bin/riscv64-unknown-elf-gcc /private/tmp/riscv-tools-test-20240207-78288-ktvp1q/hello.c
==> spike pk /private/tmp/riscv-tools-test-20240207-78288-ktvp1q/a.out
Error: riscv-software-src/riscv/riscv-tools: failed
An exception occurred within a child process:
  Minitest::Assertion: --- expected
+++ actual
@@ -1,2 +1 @@
-"bbl loader\r
-hello"
+"hello"

any clues anyone

Also, if my install is in fact OK, I need the tools to build for 32bit and 64bit - I think this page says both are supported. Do I just need to create symbolic links for risk64-unknown-elf-gcc and risk32-unknown-elf-gcc to point at risk64-elf-gcc?
any help appreciated
thanks

**Comment by sbeamer** [comment]
It is possible to build https://github.com/riscv-collab/riscv-gnu-toolchain on an arm mac. Three years later, much of the oddities about arm have been smoothed out. You do need to install a lot of dependences, and since you are not using brew, it will not do so automatically.

Out of context, I do not recognize the error message. The reference to `bbl` is surprising, since the test should only be used `pk` (and hello).
