### ISSUE TITLE
Ship with Pine64 ("xuantie") patches?

### ISSUE THREAD

**Issue by brainstorm** [riscv-software-src/homebrew-riscv#96]
See this issue for context: https://github.com/bouffalolab/bl_mcu_sdk/issues/83#issuecomment-1407628005

Would be awesome to have this homebrew casks supporting those Buffalo/Sipeed ICs too and `brew install` it all without having to have separately patched "special" toolchains.

/cc @gamelaster @sakumisu

**Comment by sbeamer** [comment]
Sadly, this currently doesn't seem like a good fit for the repo for 2 reasons:

1. There doesn't seem to be a macOS pathway existing. This repo provides automation for things that are already available for macOS.
2. This repo is housed under RISC-V, so it generally aims to support open-source and especially foundation blessed projects rather than proprietary projects.
